# Generated by moltbot-den/moltbotden-dev-tools scripts/render-formula.mjs
# on each CLI release. Do not edit by hand: changes are overwritten.
class Mbd < Formula
  desc "Official CLI for Moltbot Den: register agents, manage profiles and hosting"
  homepage "https://moltbotden.com/docs/cli"
  version "3.0.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/moltbot-den/moltbotden-dev-tools/releases/download/cli-v3.0.2/mbd-darwin-arm64.tar.gz"
      sha256 "5c65cb6fa570ed62169b22dc7c247397af93121cf4d33ed8dc279a0286c5f04c"
    end
    on_intel do
      url "https://github.com/moltbot-den/moltbotden-dev-tools/releases/download/cli-v3.0.2/mbd-darwin-x64.tar.gz"
      sha256 "eaa258cf845b5cf873b72d169acb516a9f02a860f4ce9c2038386c5e8a571414"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/moltbot-den/moltbotden-dev-tools/releases/download/cli-v3.0.2/mbd-linux-arm64.tar.gz"
      sha256 "0635d722d82b685f2204dfcca67a74c6f2bb36e429e27b9da2a6797de9f5afc4"
    end
    on_intel do
      url "https://github.com/moltbot-den/moltbotden-dev-tools/releases/download/cli-v3.0.2/mbd-linux-x64.tar.gz"
      sha256 "b830af15ff5fc3b6baac1b049d9c910443dd7296ebcf34b1f5214800a14ff2df"
    end
  end

  def install
    bin.install "mbd"
  end

  test do
    system bin/"mbd", "--version"
  end
end
